module.exports = {
  0: 'The first merit which attracts in the pages of a good writer, or the talk of a brilliant conversationalist, is the apt choice and contrast of the words employed.',
  1: 'The most powerful expression of thought and feeling through the medium of oral language must be traced to the mastery of words. Nothing is better suited to lead',
  2: 'Every speakers aim is to be heard and understood. A clear, crisp articulation holds an audience as by the spell of some irresistible power. The choice word, the',
  3: 'awake the soul if they fall upon the ear in melodious cadence but if the utterance be harsh and discordant they fail to interest, fall upon deaf ears, and are',
  4: 'the emphasizing of the relation of clause to clause, and of sentence to sentence by the systematic grouping of words. The phrase consists usually of a few words',
  5: 'which is a short sentence that forms a distinct part of a composition, paragraph, or discourse. Correct phrasing is regulated by rests, such rests as do not break',
  6: 'devoted years of his diligent life to imparting the art of correct expression in speech and writing, has provided many aids for those who would know not merely',
  7: 'that language is a temple in which the human soul is enshrined, and that it grows out of life out of its joys and its sorrows, its burdens and its necessities.',
  8: 'in the earnest but mellow tones of familiar speech. In the present volume Mr. Kleiser furnishes an additional and an exceptional aid for those who would have a mint',
  9: 'Few indeed are the books fitted to-day for the purpose of imparting this knowledge, yet two centuries ago phrase-books were esteemed as supplements to the dictionaries',
  10: 'the index to similes, the grammars, the readers, the machine-made letter-writer of mechanically perfect letters of congratulation or condolence--none are sententious',
  11: 'There are thousands of persons who may profit by the systematic study of such a book as this if they will familiarize themselves with the authors purpose by',
  12: 'Foreigners sometimes reproach us for the asperity and discordance of our speech, and in general, this reproach is just, for there are many persons who do scanty',
  13: 'If it were not so, English would be found full of beauty and harmony of sound. Familiar with the maxim, Take care of the vowels and the consonants will take care',
  14: 'The English language is so complex in character that it can scarcely be learned by rule, and can best be mastered by the study of such idioms and phrases as are',
  15: 'so must the stress or emphasis be placed on the proper word in every sentence spoken. To read or speak pleasingly one should resort to constant practise by doing',
  16: 'It is indeed a strange art to take these blocks rudely conceived for the purpose of the market or the bar  the continuity of a thought or the progress of sense.'
};

//   17: 'speakers of English into an easy control of this language than the command of the phrase that perfectly expresses the thought.',
//   18: 'of phrases at their command from which to draw when in need of the golden mean for expressing thought.',
//   19: 'correct phrase, are instruments that may reach the heart, and awake the soul if they fall upon enough to supply the need. By the compilation of this praxis',
//   20: 'as barren as seed sown on fallow ground. In language, nothing conduces so emphatically to the harmony of sounds',
//   21: 'which denote a single idea that forms a separate part of a sentence. In this respect it differs from the clause',
//   22: 'what to say, but how to say it. He has taught also what the great Holmes taught',
//   23: 'To him, as well as to the writer, the deep strong voice of man and the low sweet voice of woman are never heard',
//   24: 'and have not by any manner of means lost their value. The guide to familiar quotations',
//   25: 'a careful reading of the preliminary pages of his book. To speak in public pleasingly and readily',
//   26: 'justice to the vowel-elements of our language. Although these elements constitute its music they are continually mistreated.',
//   27: 'of themselves, a maxim that when put into practise has frequently led to the breaking-down of vowel values',
//   28: 'provided in this book; but just as care must be taken to place every accent or stress on the proper syllable',
//   29: 'so aloud in private, or preferably, in the presence of such persons as know good reading when they hear',
//   30: '',
//   31: '',
//   32: '',
//   33: '',
//   34: '',
//   35: '',
//   36: '',
//   37: '',
//   38: '',
//   39: '',
//   40: '',
//   41: '',
//   42: '',
//   43: '',
//   44: '',
//   45: '',
//   46: '',
//   47: '',
//   48: '',
//   49: '',
// };